### PR TITLE
Use async/await

### PR DESCRIPTION
**Pull request by yonihemi**
- Update swift-argument-parser to latest version.
- Use AsyncParsableCommand and async versions of CoreLocation methods.
- Change `LocatedTime`'s conformance to `Encodable` to suppress warning.
- Rename main.swift to Now.swift to be able to use `@main` attribute.

### CODE REVIEW

**Comment by erica** [comment]
This, sadly, would massively reduce the number of people who could use the program as many will not keep up to date on OS updates. The change is cool. How about you put it on a branch instead?

**Comment by yonihemi** [comment]
Thanks for reviewing!
Guess you're right, macOS updates are more difficult to keep up with.
I'll open a separate PR for bringing SAP up to date and keep this change in its' own branch.

**Comment by yonihemi** [comment]
Changed base branch to `async`.

**Comment by erica** [comment]
All tested and working?

**Comment by erica** [comment]
Also, would you please add a note into the changelog file about the branch and changes

**Comment by yonihemi** [comment]
> All tested and working?

Tested on macOS 10.15 and macOS 12, no issues.
[asciicast](https://asciinema.org/a/4Y54nt4MW0iA7RVctfnyZqElx)

**Comment by yonihemi** [comment]
> Also, would you please add a note into the changelog file about the branch and changes

Updated change log with a new minor version entry.

**Comment by erica** [comment]
Sounds good. I think the branch inherits the tag, but I'll deal with it in case it doesn't.

Thanks!

**Comment by yonihemi** [comment]
Thanks!
I had the `1.3` tag in the wrong branch so looks like it doesn't apply automatically.

**Comment by yonihemi** [comment]
Thanks!
I had the 1.3 tag in the wrong branch so looks like it doesn't apply automatically.

**Pull request merged**
